# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digispaceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='city_id',
        ),
        migrations.AddField(
            model_name='advert',
            name='city_place_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digispaceapp.City_Place'),
        ),
    ]
